GET http://localhost:3333/ola

###

GET http://localhost:3333/mulher

###

GET http://localhost:3333/mulheres

###

GET http://localhost:3333/hora

###

POST http://localhost:3333/mulheres
Content-Type: application/json

{
    "nome": "PachiCodes",
    "imagem": "https://github.com/pachicodes.png",
    "minibio": "DevRel",
    "citacao": "Que o Deno esteja com você!"
}

###

POST http://localhost:3333/mulheres
Content-Type: application/json

{
    "nome": "Monica Craveiro",
    "imagem": "https://github.com/mocraveirodev.png",
    "minibio": "Desenvolvedora Back-end",
    "citacao": "#VamosJuntes"
}

###

POST http://localhost:3333/mulheres
Content-Type: application/json

{
    "nome": "Letícia 'Levxyca'",
    "imagem": "https://github.com/levxyca.png",
    "minibio": "Community manager",
    "citacao": "Adoro fazer live coding."
}

###

POST http://localhost:3333/mulheres
Content-Type: application/json

{
    "nome": "Mulher para deletar",
    "imagem": "sem imagem",
    "minibio": "sem minibio",
    "citacao": "sem citação"
}

###

PATCH http://localhost:3333/mulheres/66312aaabaca76007383f362
Content-Type: application/json

{
    "minibio": "Desenvolvedora Back-end e Embaixadora da Progra{m}aria"
}

###

DELETE http://localhost:3333/mulheres/66312aecbaca76007383f368
