GET https://woman-dictionary.onrender.com/mulheres

###

POST https://woman-dictionary.onrender.com/mulheres
Content-Type: application/json

{
    "nome": "PachiCodes",
    "imagem": "https://github.com/pachicodes.png",
    "minibio": "DevRel",
    "citacao": "Que o Deno esteja com você!"
}

###

POST https://woman-dictionary.onrender.com/mulheres
Content-Type: application/json

{
    "nome": "Monica Craveiro",
    "imagem": "https://github.com/mocraveirodev.png",
    "minibio": "Desenvolvedora Back-end",
    "citacao": "#VamosJuntes"
}

###

POST https://woman-dictionary.onrender.com/mulheres
Content-Type: application/json

{
    "nome": "Letícia 'Levxyca'",
    "imagem": "https://github.com/levxyca.png",
    "minibio": "Community manager",
    "citacao": "Adoro fazer live coding."
}

###

POST https://woman-dictionary.onrender.com/mulheres
Content-Type: application/json

{
    "nome": "Mulher para deletar",
    "imagem": "sem imagem",
    "minibio": "sem minibio",
    "citacao": "sem citação"
}

###

PATCH https://woman-dictionary.onrender.com/mulheres/663138923bf7382cf2a92e42
Content-Type: application/json

{
    "minibio": "Desenvolvedora Back-end e Embaixadora da Progra{m}aria"
}

###

DELETE https://woman-dictionary.onrender.com/mulheres/663138f63bf7382cf2a92e4c

###

GET https://woman-dictionary.onrender.com/ola

###

GET https://woman-dictionary.onrender.com/hora

###

GET https://woman-dictionary.onrender.com/mulher