GET https://woman-dictionary.onrender.com/women

###

POST https://woman-dictionary.onrender.com/women
Content-Type: application/json

{
    "name": "PachiCodes",
    "minibio": "DevRel",
    "url": "https://github.com/pachicodes"
}

###

PATCH https://woman-dictionary.onrender.com/women/1
Content-Type: application/json

{
    "minibio": "Embaixadora da Progra{m}aria"
}

###

DELETE https://woman-dictionary.onrender.com/women/2